apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: testjava0307-stage
  namespace: openshift-gitops
  finalizers: ["resources-finalizer.argocd.argoproj.io"] 
spec:
  project: default
  source:
    path: ./components/testjava0307/overlays/stage
    repoURL: https://github.com/xjiangorg/testjava0307-gitops.git
    targetRevision: main
  destination:
    namespace: testjava0307-stage
    server: https://kubernetes.default.svc
  syncPolicy:
    managedNamespaceMetadata:
      labels: 
        argocd.argoproj.io/managed-by: openshift-gitops
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true

