apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: testjava0307-gitops
  description: This is GitOps manifest for testjava0307   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: testjava0307
    janus-idp.io/tekton: testjava0307 
    backstage.io/kubernetes-id: testjava0307 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:testjava0307
